### ISSUE TITLE
browserconfig.xml should be in the sub theme

### ISSUE THREAD

**Issue by left23** [UN-OCHA/common_design#249]
https://github.com/UN-OCHA/common_design/blob/5a05935f17bbc45a1c3225cff7f3e6322c63280b/browserconfig.xml#L1

**Comment by left23** [comment]
With the EOL for IE11 fast approaching I'm not sure we need to include this at all anymore.
https://webmasters.stackexchange.com/questions/131077/in-2020-are-browserconfig-xml-and-ieconfig-xml-now-effectively-deprecated

This file has to be placed in the root directory so it's not useful where it is now (in the base theme) without further instructions. And because it's something that should be moved to the root directory, I think it makes better sense for it to be included in the sub theme, not the base theme, if it should be included at all.

I'd opt to drop it. @rupl @lazysoundsystem @orakili Any strong opinions on this one?

**Comment by lazysoundsystem** [comment]
No strong opinions from me.

**Comment by rupl** [comment]
Happy to drop it completely, but I send zero soldiers into this one.

**Comment by orakili** [comment]
From the SO link you posted it doesn't seem clear that this file will stop being used after IE11 EOL. Also if MS stops supporting IE it doesn't mean the UN for example will switch any time soon to a different default browser. So I would keep it but, as you suggest, move it to the subtheme with some instructions about putting it at the root.

For the Drupal sites we maintain, we should open a OPS tickets to add a nginx location rewrite in the base image `/browserconfig.xml` => `/html/themes/custom/common_design_subtheme/browserconfig.xml` so that there is nothing to do regarding that file.

Re. the above, there are possibly other files that should be at the root that would benefits from this type of nginx rewrite.
