### ISSUE TITLE
Form alter hook theme suggestion should use form_id

### ISSUE THREAD

**Issue by left23** [UN-OCHA/common_design#267]
https://github.com/UN-OCHA/common_design/blob/3ffe3bf6b08bc54e89bfb0039c1b69761002fbe4/common_design.theme#L273

@orakili Your comment https://github.com/UN-OCHA/rwint9-site/pull/74#issuecomment-909421348 suggests this change:
`['#id']` should be changed to `['#form_id']`

Is this a bug or an improvement?

**Comment by orakili** [comment]
@left23 A bug. 

With `['#id']`, the suggestion will not be used if the form id is a not a single word. 

For example the taxonomy term edit form `['#id']` is `taxonomy-term-{vocabulary}-form`. Because it contains dashes, Drupal will not find a corresponding template due some `-` -> `_` (and vice versa) conversions it does internally when discovering templates and matching them with suggestions. As a result it will not use the suggestion though it will appear in the debug info.

On the other hand  `['#form_id']` contains the form id with underscores, ex: `taxonomy_term_{vocabulary}_form`, which is what Drupal expects for suggestions.
